// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3L3oKwWvmAU3fy8QX1lgtpkWkN1RnIU',
    appId: '1:514346852169:web:2152d410aab2947abd4498',
    messagingSenderId: '514346852169',
    projectId: 'paksolarmarkt',
    authDomain: 'paksolarmarkt.firebaseapp.com',
    databaseURL: 'https://paksolarmarkt-default-rtdb.firebaseio.com',
    storageBucket: 'paksolarmarkt.appspot.com',
    measurementId: 'G-DES2QD9J08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHLNaalJFiC_VvpVPRpZp2oOjjE5WKrI',
    appId: '1:514346852169:android:22725c240417f3b4bd4498',
    messagingSenderId: '514346852169',
    projectId: 'paksolarmarkt',
    databaseURL: 'https://paksolarmarkt-default-rtdb.firebaseio.com',
    storageBucket: 'paksolarmarkt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCppNP1a8vZ26nVJKxsK9TAtPj7RRUKs3U',
    appId: '1:514346852169:ios:765b4a4a2cc94c5abd4498',
    messagingSenderId: '514346852169',
    projectId: 'paksolarmarkt',
    databaseURL: 'https://paksolarmarkt-default-rtdb.firebaseio.com',
    storageBucket: 'paksolarmarkt.appspot.com',
    iosBundleId: 'com.psmapp.opalaxis',
  );
}
